# Generated by Django 5.1.4 on 2025-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='email',
            field=models.EmailField(blank=True, default='noemail@example.com', max_length=254, null=True),
        ),
    ]
