# Generated by Django 5.1.4 on 2025-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_projectidea_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('ME', 'Mechanical'), ('CE', 'Civil')], max_length=10)),
                ('domain', models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Cloud Computing', 'Cloud Computing'), ('', 'Not Specified')], max_length=50)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
